version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off  
artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:  
- provider: NuGet
  name: bleeding
  server: https://www.myget.org/F/dburriss-ci/api/v2/package
  api_key:
    secure: 'Rx7T4w1rjWYdQyNk7wKBOjylk11kMKhd8QfVnjbLdTNr+HJwDIDegUzqb5AXNWmr'
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: 'Uxpb6vXW2txHMCzcDb2NSR3ajlgPUg4dvirBrEZU25+af+Er5pZRgne5f0VeQM9r'
  on:
    branch: master
    appveyor_repo_tag: true